const FEATURED_PROJECT_LIMIT = 4;
const HOME_FEATURED_POSTS_LIMIT = 3;
const DEFAULT_FEATURED_POSTS_LIMIT = 2;
const DASHBOARD_RECENT_POSTS_LIMIT = 5;
const PROJECT_SCREENSHOT_MAX_WIDTH = 500;
const POST_IMAGE_MAX_WIDTH = 2000;

module.exports = {
  FEATURED_PROJECT_LIMIT,
  HOME_FEATURED_POSTS_LIMIT,
  DEFAULT_FEATURED_POSTS_LIMIT,
  DASHBOARD_RECENT_POSTS_LIMIT,
  PROJECT_SCREENSHOT_MAX_WIDTH,
  POST_IMAGE_MAX_WIDTH
};

